name: Deployment Pipeline

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

  
  prettierFormatCheck:
    name: Prettier checks
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Check Prettier Issues
        run: npm run prettier:check

  build:
    name: Build the application
    runs-on: ubuntu-latest
    needs: [prettierFormatCheck]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build application
        run: npm run build

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Vercel Cli
        run: npm install --global vercel@latest
      - name: Pull Vercel Environments
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
      - name: Build Artifacts for vercel
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}
      - name: Deployment Vercel
        run: vercel deploy --prebuild --token=${{secrets.VERCEL_TOKEN}}
  

